name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Pulumi
        uses: pulumi/action@v3
        with:
          command: 'login'
          secrets: 'PULUMI_ACCESS_TOKEN'

      - name: Select stack
        run: pulumi stack select dev

      - name: Create tag
        run: |
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse HEAD)
          
          # Create a tag
          git tag -a v${{ github.run_number }} -m "Release ${{ github.run_number }}"
          
          # Push the tag to GitHub
          git push origin v${{ github.run_number }}
