name: Pulumi Preview
on:
  pull_request:
    branches:
      - main
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Install NodeJs Dependencies
        run: npm install

      - name: Pulumi Login
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Verify Pulumi stack
        run: pulumi stack ls

      - name: Select Pulumi Stack
        run: pulumi stack select dev

      - name: Pulumi config
        run: pulumi config set aws:region ${{ secrets.AWS_REGION }}

      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          comment-on-pr: true
          github-token: ${{ secrets.GH_ACTION_TOKEN }}
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
