name: Pulumi
on:
  pull_request:
    branches:
      - main
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install dependencies
        run: npm install

      - run: Pulumi Preview
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: washmeapp-infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
